// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIOc2h8ze4E8fwo3C4cHpstH38s7JFgtI',
    appId: '1:1024567154769:web:51c28a9ff826430f10c070',
    messagingSenderId: '1024567154769',
    projectId: 'challenge-delivery-36077',
    authDomain: 'challenge-delivery-36077.firebaseapp.com',
    storageBucket: 'challenge-delivery-36077.appspot.com',
    measurementId: 'G-JZL1WY2N0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQT0WDTttlXmKqZKQ8cI6Znvy4isRaOXM',
    appId: '1:1024567154769:android:efcfd38a9f79056a10c070',
    messagingSenderId: '1024567154769',
    projectId: 'challenge-delivery-36077',
    storageBucket: 'challenge-delivery-36077.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4SRu-cKeh7eVt9hX5p0YiwCVg71p8POY',
    appId: '1:1024567154769:ios:970a338e64269dc010c070',
    messagingSenderId: '1024567154769',
    projectId: 'challenge-delivery-36077',
    storageBucket: 'challenge-delivery-36077.appspot.com',
    iosBundleId: 'com.example.challengeDeliveryFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4SRu-cKeh7eVt9hX5p0YiwCVg71p8POY',
    appId: '1:1024567154769:ios:90e758cff7ce6a3210c070',
    messagingSenderId: '1024567154769',
    projectId: 'challenge-delivery-36077',
    storageBucket: 'challenge-delivery-36077.appspot.com',
    iosBundleId: 'com.example.challengeDeliveryFlutter.RunnerTests',
  );
}
